version: "3.6"
services:
    web:
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: gorest
        ports:
            - 8080:8080
        volumes:
            - ./:/app
        environment:
            - Server__Host=localhost
            - Server__Port=8080
            - Database__ConnectionString=example.com
            - Database__DbName=goRest