use goTest;

db.getCollection("bicycles").insertMany([
    { code: "bicicleta-fiorenza-525cross", name:"Bicicleta Fiorenza 525 Cross", description:"BICICLETA RODADO 20 BICICLETA CROSS DE VARON NUEVO MODELO MARCA FIORENZA", origin: "ARG", unitPrice:"27199", image:"bicicleta-fiorenza-525cross" },
    { code: "bicicleta-kawasaki-kht-390-513601", name:"Bicicleta Kawasaki KHT 390", description:"Sku 513601 Bicicleta Kawasaki rodado 29 KHT 390, Cuadro de aluminio con horquilla de suspensión , Manubrio de aluminio en desnivel negro , manijas integradas ST-EF51 , Cambio 21 veloc. , Caja pedalera Cartridge , Frenos a disco , Llantas doble perfil de aluminio, origin Argentina , 6 meses de garantía., color negra con detalles verde y gris .", origin: "ARG", unitPrice:"87.299" , image:"bicicleta-kawasaki-kht-390-513601"},
    { code: "bicicleta-fiorenza-700-beach", name:"Bicicleta Fiorenza 700 Beach", description:"Sku 503436 Bicicleta modelo 700 Beach Cruiser varón Rodado 26 , Llantas Aluminio, Rayos 2 mm, Cuadro acero Hi-Ten, Freno trasero contrapedal, asiento amplio, pie de apoyo, colores :naranja, azul ,amarillo ,negro,blanco,rojo", origin: "ARG", unitPrice:"28.199", image:"bicicleta-fiorenza-700-beach" },
    { code: "bicicleta-r-29-daewoo-utah-513997", name:"Bicicleta R 29 Daewoo Utah", description:"Sku 513997 Bicicleta R 29 marca Daewoo modelo Utah marco de acero , cambios 21 velocidades , manubrio y pedales aluminio, cadena YBN, frenos de disco, llantas aluminio doble pared, cubiertas nylon 2.1, piñon 7vel", origin: "ARG", unitPrice:"69.649" , image:"bicicleta-r-29-daewoo-utah-513997"},
    { code: "502448", name:"Bicicleta paseo Dama Fiorenza 464 Tempo Blanco y Verde", description:"BICICLETA DAMA RODADO 26 BICICLETA BICOLOR INCLUYE CANASTO CON GUARDABARRO CON PORTAPAQUETE ", origin: "ARG", unitPrice:"30.499" , image:"502448"},
    { code: "513989", name:"Bicicleta R 29 Euro bike Berlin", description:"bicicleta R 29 Erobike Acero, suspencion delantera 38MM aluminio ,manubrio y stem aluminio , cadena YBN , frenos y Shifter shimano EF500, frenos delantero y trasero disco , cubiertas nylon 2.1 llanatas aluminio , piñon 7 vel.", origin: "ARG", unitPrice:"70.299" , image:"513989"},
    { code: "513865", name:"Bicicleta Kawasaki modelo KST 210", description:"Bicleta R20 MTB Kawaasaki modelo KST 210 ,Cambios Shimano 7 Velocidades ,Frenos V-BRAKE de aluminio , horquilla aluminio,llantas de aluminio , cuadro de acero , ", origin: "ARG", unitPrice:"47.499" , image:"513865"},
])