name: gorest
output_binary: ./bin/goRest.bin
build_command: go build -gcflags "all=-N -l" -o ./bin/goRest.bin ./cmd/server/
build_dir: ./cmd/server/
run_command: ""
runtime_image: golang:1.15.2
debugger_enabled: true
debugger_port: 40000
expose_ports: [8080:8080]
networks: []
environment: []
