// Code generated by dingo; DO NOT EDIT
package main

import (
	. "github.com/lucas-gio/goRest/internal/config/configuration"
	. "github.com/lucas-gio/goRest/internal/config/datasource"
	. "github.com/lucas-gio/goRest/internal/interfaces"
)

type Container struct {
	configurationService IConfigurationService
	datasourceService    IDatasourceService
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{}
}
func (container *Container) GetconfigurationService() IConfigurationService {
	if container.configurationService == nil {
		service := &ConfigurationService{}
		container.configurationService = service
	}
	return container.configurationService
}
func (container *Container) GetdatasourceService() IDatasourceService {
	if container.datasourceService == nil {
		service := &DatasourceService{}
		service.ConfigurationService = container.GetconfigurationService()
		container.datasourceService = service
	}
	return container.datasourceService
}
